
DROP TABLE IF EXISTS Historique CASCADE;
DROP TABLE IF EXISTS Position CASCADE;
DROP TABLE IF EXISTS Bateau CASCADE;


CREATE TABLE Bateau (
    MMSI VARCHAR(50) PRIMARY KEY,
    NOM VARCHAR(100),
    LONGUEUR float,
    LARGEUR float,
    DRAFT float,
    VesselType INT,
    Cargo INT
);

CREATE TABLE Historique(
    id_date SERIAL PRIMARY KEY,
    MMSI VARCHAR(50),
    FOREIGN KEY(MMSI) REFERENCES Bateau(MMSI)
    ON UPDATE CASCADE ON DELETE CASCADE,
    BaseDateTime TIMESTAMP WITHOUT TIME ZONE,
    VesselStatus INT
);


CREATE TABLE Position(
    id_position SERIAL PRIMARY KEY,
    MMSI VARCHAR(50),
    FOREIGN KEY(MMSI) REFERENCES Bateau(MMSI)
    ON UPDATE CASCADE ON DELETE CASCADE,
    id_date INT,
    FOREIGN KEY(id_date) REFERENCES Historique(id_date)
    ON UPDATE CASCADE ON DELETE CASCADE,
    LAT FLOAT,
    LON FLOAT,
    SOG FLOAT,
    COG FLOAT,
    HEADING FLOAT
);
